//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demastrazion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {

        public int id { get; set; }
        public string S { get; set; }
        public string N { get; set; }
        public string P { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
